### PR TITLE
Features create and delete flashcard sets

### PR DESCRIPTION
**Pull request by Edward-1117**
Implemented features for creating and deleting flashcard sets.

### CODE REVIEW

**Review by ThomasShimUoft — CHANGES_REQUESTED** [review]
In your two screen files, instead of System.exit(0) I would suggest changing this to <your_frame>.dispose() . System.exit(0) exits the whole program so then like the main page would also close, instead having your frame being closed is better.

**Comment by ThomasShimUoft** [comment]
Also what is InMemoryFlashcardSet? is this simply for testing?

**Comment by Edward-1117** [comment]
Thanks for your suggestion, Thomas! I changed it now so it should be good. Also, yes, the InMemoryFlashcardSet is solely for testing my use case interactor, which is like a mock database separate from the actual FlashcardSet.csv

**Review by ThomasShimUoft — APPROVED** [review]
Looks good!

**Review by ThomasShimUoft — CHANGES_REQUESTED** [review]
Hey I see that your branch is 37 commits behind main, I think it would be great if you could merge main into your branch, so that there is no merge conflicts when you merge into main.

**Review by ThomasShimUoft — CHANGES_REQUESTED** [review]
Also I think in delete use case, I think it would be good if you could delete all the flashcards in the flashcard set as well(This is because flashcards are exclusive to the flashcardset they are in, so it will be in the database being used by no one). I think as well in the delete screen, I don't think the user knows the flashcardSetId so it wouldn't be good to have that field.

**Comment by Edward-1117** [comment]
For deleting all the flashcards, that would involve overriding the deleteFlashcardSet method in FlashcardSetDataAccess right? I'm not too familiar with how Justin implemented the storing of flashcardIds into the database, so do you think he will be able to address this request? For the deletion screen, I'm not sure what would be an alternative user input besides the flashcard set's id, since for instance the titles of flashcard sets are not unique.

**Comment by ThomasShimUoft** [comment]
For deleting flashcards you simply need to use the flashcardDataAccess and call deleteFlashcard(flashcardId) and since you have all flashcardIds information in the FlashcardDsRequestModel, I think it will work. For the input, when they click the button to delete I will pass in the flashcardSetId into your main function so you do not need to worry about that. An alternative user input is simply confirm and delete buttons.

**Comment by Edward-1117** [comment]
Thanks for the clarification. I think my delete interactor should now delete the associated flashcards in Flashcards.csv as well. For the deletion screen, I got rid of the id text field and added a flashcardSetId parameter in the constructor of DeletionScreen. So, in my MainDeleteFlashcardSet, I have a placeholder id (currently set to 0) so that you can pass in the id to be deleted:
image
I haven't committed these changes yet and just wanted to check with you again if this is okay.

**Review by ThomasShimUoft — APPROVED** [review]
Everything looks good, I will change your placeholder once you merge into main.

**Comment by Edward-1117** [comment]
Awesome! Thank you for the feedback. I'm currently having issues merging main into my branch, so I'll make a separate pull request in a couple minutes and if you can approve that request instead that would be great.

**Pull request closed without merging**
