### PR TITLE
Feature 1 and 2 login and signup

### PR DESCRIPTION
**Pull request by uoftguy**
Added login and signup package

### CODE REVIEW

**Review by jempio — COMMENTED** [review]
looks good

**Review by jempio — DISMISSED** [review]

**Review by ThomasShimUoft — COMMENTED** [review]
I am assuming a lot of the empty java classes are to be implemented. But everything looks good structure-wise.

**Comment by lucasprates74** [comment]
Add the User's flashcardId map and username to the UserResponseModel so the main page can access the data

**Review by jempio — COMMENTED** [review]
Looks good so far. Make changes to flashcardSets datatype to List<Integer> and rename to flashcardSetIds instead

**Review by jempio — COMMENTED** [review]
I also believe we don't need a date time creation for users

**Comment by lucasprates74** [comment]
You should refactor and put the folder loginAndSignupUseCaseScreens inside the folder loginAndSignupUseCase

**Review by jempio — DISMISSED** [review]
Changes and conflicts are resolved, ready to merge into main

**Review by jempio — APPROVED** [review]

**Comment by uoftguy** [comment]
Self Note:

Single responsibility  principle (SRP): Each class is responsible for 1 specific task, for example interactor is meant to deal with the attributes but its still 1 task and otherwise each class still has one responsibility.
Open/closed principle (OCP): Having the user and common user classes in the entities segregated aspect allows for this principle as even in other code it treats themselves as an extension of the code rather than directly interacting and altering it. Hence, allowing for stronger implementation of this principle.
Liskov substitution  principle (LSP): Having common user be heightened usage of the user class allows for this principle as it allows for the implementers to modify the code with the common user class but doesn't modify or remove the basic foundation of the program and this use case.
Interface  segregation  principle (ISP): Having the input and output boundary interfaces keep a minimal element to them to conduct only the absolute necessary and not expanding beyond allows for this principle. Thus this implementation allows for re-implementation in other aspects of the code to not impact as much.
Dependency inversion  principle (DIP): Using attributes of the clean architecture with the data boundary interfaces, data access interfaces and controllers/presenters allow for this principle as there is as far from a direct relation within higher-level classes to lower-level classes through these abstraction layers mentioned previously.

**Pull request merged**
