### PR TITLE
Feature edit main page WindowListener Bug fix

### PR DESCRIPTION
**Pull request by ThomasShimUoft**
Fixed a bug where the WindowListener on the main page was not following the new edit pages created when refreshing the edit page. So as a fix, the main page refreshes only when the edit main page is closed via the window close button on the top right.

### CODE REVIEW

**Review by jempio — APPROVED** [review]
Changes look ready to merge. Implementation follows solid and will be a better for users.

**Review by lucasprates74 — DISMISSED** [review]
These UI changes look good Thomas- just make sure to fix the csv merge conflicts

**Comment by ThomasShimUoft** [comment]
This branch also contains the new UI design for the flashcards in the edit main page.

**Comment by lucasprates74** [comment]
Actually make sure to make the home page style consistent with the editor page style before merge

**Review by lucasprates74 — APPROVED** [review]
New UI seems good

**Pull request merged**
